[general]
import = [
	"./includes/color-scheme.toml",
	"./includes/font.toml",
	"./includes/misc.toml",
]

[terminal.shell]
# https://github.com/alacritty/alacritty/issues/7615#issuecomment-2013979170
program = "pwsh"
args = ["-WorkingDirectory ~",]
