"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](color_orange_dim)\
$os\
([](bg:prev_bg fg:prev_fg)$username)\
([](bg:prev_bg fg:prev_fg)$sudo)\
[](bg:color_yellow_dim fg:prev_bg)\
$directory\
[](bg:color_aqua_dim fg:prev_bg)\
$git_branch\
$git_status\
[](color_aqua_dim)\
$fill\
[](color_bg1)\
($status[ ](fg:color_fg bg:prev_bg))\
$cmd_duration\
$direnv\
[](fg:color_blue_dim bg:color_bg1)\
$docker_context\
$python\
$rust\
$nodejs\
[](fg:color_orange bg:color_blue_dim)\
$hostname\
[](fg:color_bg1 bg:color_orange)\
$time\
[](prev_bg)\
$line_break$character\
"""

palette = 'gruvbox_dark'

[palettes.gruvbox_dark]

color_bg_h = '#1d2021'
color_bg = '#282828'
color_bg_s = '#32302f'
color_bg1 = '#3c3836'
color_bg2 = '#504945'
color_bg3 = '#665c54'
color_bg4 = '#7c6f64'

color_fg = '#fbf1c7'
color_fg1 = '#ebdbb2'
color_fg2 = '#d5c4a1'
color_fg3 = '#bdae93'
color_fg4 = '#a89984'

color_red = '#fb4934'
color_red_dim = '#cc2412'

color_green = '#b8bb26'
color_green_dim = '#98971a'

color_yellow = '#fabd2f'
color_yellow_dim = '#d79921'

color_blue = '#83a598'
color_blue_dim = '#458588'

color_purple = '#d3869b'
color_purple_dim = '#b16286'

color_aqua = '#8ec07c'
color_aqua_dim = '#689d6a'

color_gray = '#928374'
color_gray_dim = '#a89984'

color_orange = '#fe8019'
color_orange_dim = '#d65d0e'

[os]
format = '[$symbol ]($style)'
disabled = false
style = "bg:color_orange_dim fg:color_bg"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
Pop = ""

[username]
show_always = false
style_user = "bg:color_orange_dim fg:color_bg"
style_root = "bg:color_orange_dim fg:color_bg"
format = "[ $user ]($style)"

[sudo]
disabled = false
style = "bg:prev_bg"
format = "[ $symbol]($style)"

[directory]
style = " bg:color_yellow_dim fg:color_bg"
format = "[ $path ]($style)"
truncation_length = 3
truncate_to_repo = true
truncation_symbol = "…/"

[directory.substitutions]
"documents" = "󰈙 "
"downloads" = " "
"music" = "󰝚 "
"pictures" = " "
"dev" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:color_aqua_dim"
format = '[[ $symbol $branch ](fg:color_bg_h bg:color_aqua_dim)]($style)'

[git_status]
style = "fg:color_bg_h bg:color_aqua_dim"
format = '[$all_status$ahead_behind]($style)'
conflicted = '=$count '
ahead = '⇡${count}'
behind = '⇣${count}'
diverged = '(⇡${ahead_count}⇣${behind_count}) '
untracked = '(?$count )'
stashed = '(\$$count )'
modified = '(!$count )'
staged = '(+$count )'
renamed	= '(»$count )'
deleted	= '(✘$count )'

[fill]
style = 'bold color_bg1'
symbol = '┄'

[status]
style = 'fg:color_fg bg:color_bg1'
success_style = 'fg:color_green bg:color_bg1'
failure_style = 'fg:color_red bg:color_bg1'
format = '[ [$symbol$status]($style)](bg:color_bg1 fg:color_fg)'
map_symbol = true
disabled = false

[cmd_duration]
disabled = false
style = 'fg:color_fg bg:color_bg1'
format = '[  $duration ]($style)'

[nodejs]
symbol = " "
style = "fg:color_bg_h bg:color_blue_dim"
format = '[ $symbol($version) ]($style)'
version_format= '${raw}'

[rust]
symbol = ""
style = "fg:color_bg_h bg:color_blue_dim"
format = '[ $symbol($version) ]($style)'

[python]
symbol = ""
style = "fg:color_bg_h bg:color_blue_dim"
format = '[ $symbol($version) ]($style)'

[docker_context]
symbol = ""
style = "fg:color_bg_h bg:color_blue_dim"
format = '[ $symbol($version) ]($style)'

[time]
disabled = false
time_format = "%R"
use_12hr = false
style = "fg:color_fg bg:color_bg1"
format = "[  $time ]($style)"

[hostname]
ssh_only = true
style = 'fg:color_bg_h bg:color_orange'
format = "[ $ssh_symbol$hostname ]($style)"

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:color_green)'
error_symbol = '[](bold fg:color_red)'
